### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Chameleon-Coder** [RayhanADev/Personal-Website#1]
I enjoy furrets. Furrets are awesome in my opinion.
Also, cool website!

**Comment by rayhanadev** [comment]
Thank you, I appreciate it! 😅 but let's keep issues to bugs.

If you have Discord, I'm `_hayrenryzm#7039` we can talk there :). I'm also in the [Replit Discord Server](https://discord.gg/replit) you can ping me with `@hay`.
